### ISSUE TITLE
Distributed tracing not monitoring Service Bus

### ISSUE THREAD

**Issue by sigmaadam** [microsoft/ApplicationInsights-node.js#796]
Hi,

I'm using the following libs:
 
- applicationinsights: 2.1.4

- @azure/service-bus: 7.3.0

I also have many micro-services, some of them pass events via service bus topic.
When I'm searching for transaction in azure appInsight console, the transaction cut when we publish message to topic. 
It doesn't do the distributed tracing and continue the flow in the consumers.
I thought this is done behind the scene automatically.

If there was any option to get the operationID manually, I could implement it by myself, by passing it throw applicationSetting and run context with CorrelationContextManager.runWithContext method, but I didn't find any way to get it.

Any solution to support distributed tracing?

Thanks

**Comment by sigmaadam** [comment]
Updates:

After installing manually the following libs:
https://www.npmjs.com/package/@opentelemetry/api

now I can see the publish message to service bus, image below:

<img width="484" alt="Screen Shot 2021-07-28 at 22 29 03" src="https://user-images.githubusercontent.com/46670025/127384091-1e276ecf-1f4a-463e-8b26-e724da2c92d9.png">

This send event, return 1 (not success) even the request was succeed.
The issue is that it's not connected to no operation.

Beside that the subscription of the service bus, that processed the messages, doesn't connected to same operation, I even try to use same logic as this example (with diagnosic-id as parent operation ID):
https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing?tabs=net-standard-sdk-2

But the processed message was not connected to no operation.

**Comment by hectorhdzg** [comment]
@sigmaadam regarding second issue with wrong status, that must be resolved in next release as it was fixed in this [PR](https://github.com/microsoft/ApplicationInsights-node.js/pull/797), we still need to investigate about distributed tracing issue, we will add updates here.

**Comment by vinutha93bnvs** [comment]
@hectorhdzg 
appinsights: 2.1.5
@azure/service-bus: 7.3.0

I still do not see the dependency call success or distributed tracing being solved. 

1. core tracing enabled
![image](https://user-images.githubusercontent.com/26425752/128967907-891ffffb-4a8d-4c41-8f85-8137fd8ed148.png)

![image](https://user-images.githubusercontent.com/26425752/128967775-fa3e6c61-bde9-4c02-be42-4dabaec69e60.png)


![image](https://user-images.githubusercontent.com/26425752/128967716-4d62f46c-abff-4ae8-8541-14f0a7086987.png)

**Comment by hectorhdzg** [comment]
thanks @vinutha93bnvs we use OpenTelemetry internal implementation in Azure SDK to auto generate telemetry in Application Insights, apparently @azure/service-bus is not setting the state of their spans, in the meantime @xiao-lix updated our logic to consider successful anything that was not marked as failure even if the status is never set, this must take care of wrong status in Application Insights.

**Comment by vinutha93bnvs** [comment]
@hectorhdzg
When can we expect this change release

**Comment by hectorhdzg** [comment]
@vinutha93bnvs we have monthly releases for this SDK, you can expect a new version at the end of the month.

**Comment by sigmaadam** [comment]
In version applicationinsights: 2.1.5 it stopped sending the "send" events of service bus.
In version applicationinsights: 2.1.4 it worked (with response of 1)  but it did see the send event in application insight.

**Comment by sigmaadam** [comment]
Hi, 

This time it return 409 error:
![Screen Shot 2021-08-29 at 7 29 27](https://user-images.githubusercontent.com/46670025/131238635-21f82d7c-24a9-484d-b7c8-82d767ce5fb9.png)

**Comment by hectorhdzg** [comment]
@sigmaadam this issue is definitely different, is possible you are getting a real 409 error in your service? I cannot think of any scenario we add random response codes to the telemetry

**Comment by sigmaadam** [comment]
All of my calls are getting 409, even I'm not getting any error or exception in my code

I'm using the following service bus library:
"@azure/service-bus": "^7.3.0",

Their signature is as follow:
sendMessages(messages: ServiceBusMessage | ServiceBusMessage[] | ServiceBusMessageBatch | AmqpAnnotatedMessage | AmqpAnnotatedMessage[], options?: OperationOptionsBase): Promise<void>

In caes of an error they are sending exception,
I'm not getting any exception, I'm getting success.

So the 409 is not real.

**Comment by hectorhdzg** [comment]
This sound like an issue on how Service Bus package creates OpenTelemetry Spans we use to generate the telemetry in this SDK, I'm not able to repro with same versions, I'm getting resultCode=1 that means they are not adding correct attributes to the Span to include information like the HTTP result code, it will be good to track on their side so they can investigate further
